### ISSUE TITLE
Fails on Windows

### ISSUE THREAD

**Issue by koppor** [GuillaumeFalourd/setup-rsync#2]
> Error: Process completed with exit code 127.

See also https://github.com/GuillaumeFalourd/setup-rsync/actions/runs/5735432467

Work around: Use https://github.com/egor-tensin/setup-cygwin

```yaml
- name: Set up rsync
  uses: egor-tensin/setup-cygwin@v4
  with:
    packages: rsync
```

Other workaround:

    choco install --no-progress rsync

In case the latter is used, remember to use `-e 'C:\ProgramData\chocolatey\lib\rsync\tools\bin\ssh.exe'` as ssh client. Otherwise, one can get

    rsync: connection unexpectedly closed (0 bytes received so far) [sender]
    rsync error: error in rsync protocol data stream (code 12) at io.c(231)    [sender=3.2.7]
