### ISSUE TITLE
Use @v1 GitHub Actions tag

### ISSUE THREAD

**Issue by jcbhmr** [GuillaumeFalourd/setup-rsync#5]
I think it would be a good idea to follow the  GitHub Actions convention of using `- uses: user/repo@vX.Y.Z` for specific releases with a `- uses: user/repo@vX` super-tag that automatically follows the latest `X.*.*` release. This is how all(?) of the @actions GitHub Actions work along with most of the community actions that I've used.

Here's an example GitHub Actions workflow that the @actions (official) org uses to automate the updating of `vN` tags to follow the latest `vN.*.*` release via GitHub releases:

```yml
name: Release new action version

on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      TAG_NAME:
        description: 'Tag name that the major tag will point to'
        required: true

env:
  TAG_NAME: ${{ github.event.inputs.TAG_NAME || github.event.release.tag_name }}

jobs:
  update_tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/publish-action@v0.3.0
        with:
          source-tag: ${{ env.TAG_NAME }}
```

https://github.com/actions/publish-action/blob/main/.github/workflows/release-new-action-version.yml

End goal is to be able to do this:

```yml
- uses: GuillaumeFalourd/setup-rsync@v1
```
